eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8091
spring:
  application:
    name: customer
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/customers
    hikari:
      username: root
      password: ameda
  jpa:
    hibernate:
      ddl-auto: create
    database:  postgresql
#    database-platform: org.hibernate.dialect.postgreSQL10Dialect